import com.mathworks.toolbox.javabuilder.*;
import JavaTestCall.TestMatClass;
import java.time.Instant;
import java.time.Duration;

/**
 *
 * Sample driver code that is integrated with a compiled MATLAB function
 * generated by MATLAB Compiler SDK.
 *
 * Refer to the MATLAB Compiler SDK documentation for more
 * information.
 *
 * @see com.mathworks.toolbox.javabuilder.MWArray
 *
 */
public class javaTest_CallSample {

	private static TestMatClass testmatclassInstance;

	private static void setup() throws MWException {
		Instant startInstant = Instant.now();
		testmatclassInstance = new TestMatClass();
		Instant endInstant = Instant.now();
		Duration duration = Duration.between(startInstant, endInstant);
		System.out.println("Execution time to initialize: " + duration.toMillis() + " milliseconds");
	}

	/**
	 * Sample code for {@link TestMatClass#javeTest(int, Object...)}.
	 */
	public static void javeTestExample() {
		MWArray in_full_pathIn = null;
		MWArray out_full_pathIn = null;
		MWArray optionIn = null;
		MWNumericArray statusOut = null;
		Object[] results = null;
		int i = 0;
		while (i < 10) {
			try {			
				Instant startInstant = Instant.now();
				String in_full_pathInData = "test_image.tif";
				in_full_pathIn = new MWCharArray(in_full_pathInData);
				String optionInData = "Low";
					String out_full_pathInData = "out_" + i + ".tif";
					out_full_pathIn = new MWCharArray(out_full_pathInData);
					optionIn = new MWCharArray(optionInData);
					results = testmatclassInstance.javeTest(1, in_full_pathIn, out_full_pathIn, optionIn);
					if (results[0] instanceof MWNumericArray) {
						statusOut = (MWNumericArray) results[0];
					}
					
					Instant endInstant = Instant.now();
					Duration duration = Duration.between(startInstant, endInstant);
					System.out.println("Execution time to initialize: " + duration.toMillis() + " milliseconds");
					//System.out.println(statusOut);
			} catch (Exception e) {
				e.printStackTrace();
			} finally {
				// Dispose of native resources
				MWArray.disposeArray(in_full_pathIn);
				MWArray.disposeArray(out_full_pathIn);
				MWArray.disposeArray(optionIn);
				MWArray.disposeArray(results);
			}

			i++;
		}
	}

	public static void main(String[] args) {
		try {
			setup();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
		try {
			javeTestExample();
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		} finally {
			// Dispose of native resources
			testmatclassInstance.dispose();
		}
	}

}
